version: '3.6'

services: 
    api:
        build: .
        depends_on: 
            - db
        networks: 
            - default
        ports: 
            - 5000:5000
        restart: always
        volumes:
            - ./migrations:/code/migrations
        
    db:
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: postgres
        image: postgres:latest
        networks: 
            - default
        ports: 
            - 5432:5432
        restart: always
        volumes: 
            - ./postgres-data:/var/lib/postgresql/data